# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    #performance_test:
    name: ExecutingSanity

     # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Read File
        id: package
        uses: jaywcjlove/github-action-read-file@main
        with:
         path: TestParameters.txt

      - name: File Read
        run: |
             awk -F "," 'NR>1{print $1}' ./TestParameters.txt >> user.txt
             VUsers="cat user.txt"
             awk -F "," 'NR>1{print $3}' ./TestParameters.txt >> iter.txt
             Iterations="cat iter.txt"
             awk -F "," 'NR>1{print $2}' ./TestParameters.txt >> ramp.txt
             Rampup="cat ramp.txt"
              echo "This is $VUsers Users"
              echo "This is $Iterations Iterations"
              echo "This is $Rampup Rampup"
