# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Create reports directory
        run: mkdir reports
      - name: PerfAction for JMeter
        # You may pin to the exact commit or the version.
        # uses: QAInsights/PerfAction@5a3c503bff845dd019d4b6e30d71f4585494a2ea
        uses: QAInsights/PerfAction@v5.6.2
        with:
          # JMeter test plan to execute
          test-plan-path: './jmeterjenkins.jmx'
          # Where to store the results e.g., result.csv
          results-file: ./reports/result.jtl
          args: "-e -o ./reports/html"

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: reports/result.jtl
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: reports/html
          if-no-files-found: error

      - name: Mailgun Action
  # You may pin to the exact commit or the version.
  # uses: vineetchoudhary/mailgun-action@a25d236b31970d671006f4ced13b2c88af390753
        uses: vineetchoudhary/mailgun-action@v1.1
        with:
    # Mailgun API Key
          api-key: 1b9cd3adab76e4d1859b4a510beac9bb-a2dd40a3-9ce3a97e
    # Your Domain Name
          domain: smtp.gmail.com
    # Email address of the recipient(s). Example: bob@host.com. You can use commas to separate multiple recipients.
          to: chiragmathur2014@gmail.com
    # Email address to recieve carbon copies. Example: bob@host.com. You can use commas to separate multiple recipients.
          #cc: # optional
    # The email that will be shown as sender. Default will be hello@+your domain name. Like - hello@example.com
         # from: # optional
    # Email subject.
          subject: This is mailgun test email
    # Body of the email (HTML Supported).
          body: This is mailgun test email
